import Config

# Configure your database
# WebAuthn / passkeys. localhost is a "secure context" so HTTP works in dev.
config :wax_,
  origin: "http://localhost:4000",
  rp_id: "localhost"

# Encryption at rest (Cloak). DEV-ONLY default key — protects only local throwaway
# data. Override with PASS_CLOAK_KEY. Production requires a real key (see runtime.exs).
config :pass, Pass.Encryption.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1",
       key:
         Base.decode64!(
           System.get_env("PASS_CLOAK_KEY") || "SnnlI94TTRVzlJCBKEzbmwylfVJT8rfkOo1kXFmKNf0="
         )}
  ]

# Local dev DB password, read from the environment so no secret is committed.
# Set PASS_DB_PASSWORD in your shell, or put it in an untracked .env file at the
# project root (useful for editors/preview runners that spawn the server without
# a shell profile). Defaults to the conventional "postgres".
dotenv =
  case File.read(Path.expand("../.env", __DIR__)) do
    {:ok, contents} ->
      for line <- String.split(contents, ~r/\r?\n/, trim: true),
          not String.starts_with?(line, "#"),
          [key, value] <- [String.split(line, "=", parts: 2)],
          into: %{} do
        {String.trim(key), String.trim(value)}
      end

    _ ->
      %{}
  end

db_password = System.get_env("PASS_DB_PASSWORD") || dotenv["PASS_DB_PASSWORD"] || "postgres"

config :pass, Pass.Repo,
  username: "postgres",
  password: db_password,
  hostname: "localhost",
  database: "pass_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pass, PassWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "nq+NM32LmhF5ojr14Az0p/OXYWoyBhTHKiXzasuWqqhJAFN9s8e02kUyi6tPmeZ3",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pass, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pass, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :pass, PassWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/pass_web/router\.ex$",
      ~r"lib/pass_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :pass, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
